### ISSUE TITLE
Determine File Structure

### ISSUE THREAD

**Issue by fidget1** [AKirkland616/CS4900-CompGeo#10]

**Comment by ghost** [comment]
Proposed file structure:

**CompGeo/**
|
**|--backend/**
**|----ds/**
|------[ds].py
|------test_[ds].py
|------...
|
**|----algs/**
|------[alg].py
|------test_[alg].py
|------...
|
**|----api/**
|------[api].py
|------test_[api].py
|------...
|
**|--frontend/**
|----...

**ds/** would contain class definitions for all of the relevant data structures (Point.py, Line_Segment.py, etc.), **algs/** would contain scripts for all of the necessary algorithms, one per problem (line_intersect.py, closest_pair.py, etc.), and **api/** would handle the instantiation of CompGeo data structures and communicate with the frontend.

We could put all of the "test_[file].py" files in a separate **Test/** directory. We would probably need two test directories in that case: one for the frontend, the other for the backend.

**Comment by ghost** [comment]
Alternative (test files in a separate directory):

**CompGeo/**
|
**|--backend/**
**|----ds/**
|------[ds].py
|------...
|
**|----algs/**
|------[alg].py
|------...
|
**|----api/**
|------[api].py
|------...
**|----test/**
|------test_[ds].py
|------test_[api].py
|------test_[alg].py
|
**|--frontend/**
|----...

**Comment by fidget1** [comment]
We'll go with the alternative.
