### ISSUE TITLE
Create form/template for stories

### ISSUE THREAD

**Issue by fidget1** [AKirkland616/CS4900-CompGeo#9]

**Comment by fidget1** [comment]
Stories should be created as a document apart from the Project board, issues, and linked to (technical) issues.

**Comment by ghost** [comment]
Created a form (MS Forms) that populates an Excel spreadsheet whenever a new response is submitted. See MS Teams chat for a link.

**Comment by ghost** [comment]
Alternatively, we could create a "story" label and write the stories as titles. That way, we can link them to milestones/issues directly in GitHub.
